// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (account_id, debit, credit, transaction_id, operation_type, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, debit, credit, transaction_id, operation_type, description, created_at
`

type CreateEntryParams struct {
	AccountID     uuid.UUID      `json:"account_id"`
	Debit         string         `json:"debit"`
	Credit        string         `json:"credit"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	OperationType string         `json:"operation_type"`
	Description   sql.NullString `json:"description"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
		arg.TransactionID,
		arg.OperationType,
		arg.Description,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
		&i.TransactionID,
		&i.OperationType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT id, account_id, debit, credit, transaction_id, operation_type, description, created_at FROM entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.TransactionID,
			&i.OperationType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByTransaction = `-- name: ListEntriesByTransaction :many
SELECT id, account_id, debit, credit, transaction_id, operation_type, description, created_at FROM entries
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) ListEntriesByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.TransactionID,
			&i.OperationType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
