// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID     `json:"id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
	Name      string        `json:"name"`
	Balance   string        `json:"balance"`
	Currency  string        `json:"currency"`
	IsSystem  bool          `json:"is_system"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Entry struct {
	ID            uuid.UUID      `json:"id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Debit         string         `json:"debit"`
	Credit        string         `json:"credit"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	OperationType string         `json:"operation_type"`
	Description   sql.NullString `json:"description"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type User struct {
	ID             uuid.UUID    `json:"id"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	CreatedAt      sql.NullTime `json:"created_at"`
}
