// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	// lock prevents concurrent transactions from reading a stale balance.
	GetAccountBalance(ctx context.Context, accountID uuid.UUID) (string, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetSettlementAccount(ctx context.Context) (Account, error)
	GetSettlementAccountForUpdate(ctx context.Context) (Account, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// locks row for update, prevents TOCTOU races
	ListAccountsByOwner(ctx context.Context, ownerID uuid.NullUUID) ([]Account, error)
	ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]Entry, error)
	ListEntriesByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Entry, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
}

var _ Querier = (*Queries)(nil)
